# -*- coding: utf-8 -*-
"""api.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rn7wsff617McvH6elhsIlVN9uYYxefWR
"""

from flask import Flask, request, jsonify
import joblib
import numpy as np

app = Flask(__name__)

model_obj = joblib.load('models/model_v1.pkl')
pipeline = model_obj['pipeline']
threshold = model_obj['threshold']

FEATURE_NAMES = [
    'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE',
    'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6',
    'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6',
    'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6'
]

@app.route('/predict', methods = ['POST'])
def predict():

    try:
        data = request.get_json()
        features = preprocess_input(data)
        probability = float(pipeline.predict_proba(features)[0][1])
        prediction = int(probability >= threshold)

        return jsonify({
            'prediction': prediction,
            'probability': round(probability, 4),
            'threshold': round(threshold, 2)
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 400

@app.route('/health', methods=['GET'])
def health():

    return jsonify({'status': 'healthy'}), 200

def preprocess_input(data):

    if 'features' in data:
        return np.array(data['features']).reshape(1, -1)
    return np.array([data[key] for key in FEATURE_NAMES]).reshape(1, -1)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port = 5000, debug = False)

