# -*- coding: utf-8 -*-
"""model_handler.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rn7wsff617McvH6elhsIlVN9uYYxefWR
"""

import joblib
import numpy as np

model_path = 'models/model_v1.pkl'

_model = None

def get_model():
    global _model
    if _model is None:
        if not os.path.exists(model_path):
            raise FileNotFoundError(f'Model not found at {model_path}')
        _model = joblib.load(model_path)
    return _model

def predict(features: list):
    model_obj = get_model()
    pipeline = model_obj['pipeline']
    threshold = model_obj['threshold']

    X = np.array(features).reshape(1, -1)
    probability = float(pipeline.predict_proba(X)[0][1])
    prediction = int(probability >= threshold)

    return {
        'prediction': prediction,
        'probability': round(probability, 4),
        'threshold': round(threshold, 2),
    }

